### ISSUE TITLE
Меньше слайдер на 40%

### ISSUE THREAD

**Issue by AndreyGinger** [AndreyGinger/vr-sport-prompt#10]
![unnamed](https://user-images.githubusercontent.com/39490820/40494064-ac2c1c54-5f7c-11e8-9eae-c237016e9ed3.jpg)

Вот именно так смотрит заказчик. Просит размер карточек сделать на 40% меньше. Я уменьшу картинки сам и загружу. Тебе нужно только отследить чтобы расстояние между ними не поплыло и все остальные части слайдера чтобы оказались на своих местах.

**Comment by K073** [comment]
![image](https://user-images.githubusercontent.com/22838146/40496528-c8c5330e-5f9b-11e8-97db-aaadda78eefc.png)
